### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mbazzo** [garciaolais/i2c-netcore#1]
Hello budy, how are you?
You would have an example of using it along with c ++ (i2c-dotnet.so).
I am not able to compile c ++
Thank you

**Comment by garciaolais** [comment]
Hi Marcos.

Sorry :( but I don't have any example with c++. But I can prepare a little example, give me a few days because in this moment I don't have any I2C sensor to test it.

**Comment by mbazzo** [comment]
I'm trying to use it to write on a 16x2 lcd

I'm trying to do in C #

thank you

**Comment by garciaolais** [comment]
I'm tested it with BMP180 temperature sensor and SSD1306 oled display. Both with C#

**Comment by garciaolais** [comment]
> 
> 
> Hello budy, how are you?
> You would have an example of using it along with c ++ (i2c-dotnet.so).
> I am not able to compile c ++
> Thank you

Hi , I made a little example in c++ using the "i2c-dotnet.so" lib.

You can check it out https://github.com/garciaolais/bmp180-cpp

Note 1:  I tested in a Raspberry Pi 3 with a BMP180 temperature sensor
Note 2 : Please note I am not a c++ programer, I did my best.
