### ISSUE TITLE
有 i2c-dotnet.so 的源代码吗？

### ISSUE THREAD

**Issue by xiongzhaoxu** [garciaolais/i2c-netcore#2]
有 i2c-dotnet.so 的源代码吗？

**Comment by garciaolais** [comment]
Hi, the i2c-dotnet.so source code is here ->

https://github.com/garciaolais/i2c-dotnet-wrapper

**Comment by xiongzhaoxu** [comment]
got, thx.

**Comment by xiongzhaoxu** [comment]
.net Core 调用 PCA9685 这个有实现过吗？

**Comment by garciaolais** [comment]
I only implemented for these decides.

Temperature sensor bmp180 
https://github.com/garciaolais/bmp180-dotnet-example

Oled display 128x64 ssd1306
https://github.com/garciaolais/ssd130-dotnet-example
